global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using EShop.Domain.Aggregates.BuyerAggregate;
global using EShop.Domain.Common;
global using EShop.Domain.Enums;
global using EShop.Domain.Exceptions;