global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using EShop.Application.Entities;
global using EShop.Application.Services;
global using EShop.Shared.ResponseModels.Common;
global using Microsoft.EntityFrameworkCore;